---
- name: Set controller host name and port
  set_fact:
    _automation_controller_hostname: "{{ ansible_host }}:{{ aap_port | default('443') }}"
    _automation_controller_username: admin
    _automation_controller_password: "{{ admin_password }}"

- name: Add project in Controller
  ansible.controller.project:
    controller_username: "{{ _automation_controller_username }}"
    controller_password: "{{ _automation_controller_password }}"
    controller_host: "https://{{ _automation_controller_hostname }}"
    validate_certs: false
    name: Cisco Telemetry
    organization: Default
    scm_type: git
    scm_url: https://github.com/zjpeterson/ansible-cisco-telemetry.git

- name: Add EE in Controller
  ansible.controller.execution_environment:
    controller_username: "{{ _automation_controller_username }}"
    controller_password: "{{ _automation_controller_password }}"
    controller_host: "https://{{ _automation_controller_hostname }}"
    validate_certs: false
    name: Lab EE
    image: quay.io/zachp/lab-ee

- name: Get Controller token
  ansible.controller.token:
    controller_username: "{{ _automation_controller_username }}"
    controller_password: "{{ _automation_controller_password }}"
    controller_host: "https://{{ _automation_controller_hostname }}"
    validate_certs: false
    description: EDA Controller
    scope: write

- name: Add Controller token in EDA
  ansible.eda.credential:
    controller_username: "{{ _automation_controller_username }}"
    controller_password: "{{ _automation_controller_password }}"
    controller_host: "https://{{ _automation_controller_hostname }}"
    validate_certs: false
    name: Automation Controller
    organization: Default
    credential_type_name: Red Hat Ansible Automation Platform
    inputs:
      oauth_token: "{{ controller_token.token }}"
      host: "https://{{ _automation_controller_hostname }}/api/controller/"

- name: Add project in EDA
  ansible.eda.project:
    controller_username: "{{ _automation_controller_username }}"
    controller_password: "{{ _automation_controller_password }}"
    controller_host: "https://{{ _automation_controller_hostname }}"
    validate_certs: false
    name: Cisco Telemetry
    organization: Default
    url: https://github.com/zjpeterson/ansible-cisco-telemetry.git

- name: Add upstream DE
  ansible.eda.decision_environment:
    controller_username: "{{ _automation_controller_username }}"
    controller_password: "{{ _automation_controller_password }}"
    controller_host: "https://{{ _automation_controller_hostname }}"
    validate_certs: false
    name: Lab DE
    organization: Default
    image_url: quay.io/ansible/ansible-rulebook:v1.1.3
