---
- name: Set controller host name and port
  set_fact:
    _automation_controller_hostname: "{{ ansible_host }}:{{ aap_port | default('443') }}"
    _automation_controller_username: admin
    _automation_controller_password: "{{ admin_password }}"

- name: Add project in Controller
  ansible.controller.project:
    controller_username: "{{ _automation_controller_username }}"
    controller_password: "{{ _automation_controller_password }}"
    controller_host: "https://{{ _automation_controller_hostname }}"
    validate_certs: false
    name: Cisco Telemetry
    organization: Default
    scm_type: git
    scm_url: https://github.com/zjpeterson/ansible-cisco-telemetry.git

- name: Add EE in Controller
  ansible.controller.execution_environment:
    controller_username: "{{ _automation_controller_username }}"
    controller_password: "{{ _automation_controller_password }}"
    controller_host: "https://{{ _automation_controller_hostname }}"
    validate_certs: false
    name: Lab EE
    image: quay.io/zachp/lab-ee

- name: Add vars to Controller hosts
  vars:
    _new_vars: "{{ lookup('file', role_path + '/files/host_vars/' + item.name + '.yml') | from_yaml }}"
  ansible.controller.host:
    controller_username: "{{ _automation_controller_username }}"
    controller_password: "{{ _automation_controller_password }}"
    controller_host: "https://{{ _automation_controller_hostname }}"
    validate_certs: false
    name: "{{ item.name }}"
    inventory: Workshop Inventory
    variables: "{{ item.variables | from_yaml | combine(_new_vars) }}"
  loop: "{{ lookup('ansible.controller.controller_api', 'hosts', host=_automation_controller_hostname, username=_automation_controller_username, password=_automation_controller_password, verify_ssl=False) }}"
  when: item.name in ['rtr1', 'rtr2']

- name: Get Controller token
  ansible.controller.token:
    controller_username: "{{ _automation_controller_username }}"
    controller_password: "{{ _automation_controller_password }}"
    controller_host: "https://{{ _automation_controller_hostname }}"
    validate_certs: false
    description: EDA Controller
    scope: write

- name: Add Controller token in EDA
  ansible.eda.credential:
    controller_username: "{{ _automation_controller_username }}"
    controller_password: "{{ _automation_controller_password }}"
    controller_host: "https://{{ _automation_controller_hostname }}"
    validate_certs: false
    name: Automation Controller
    organization: Default
    credential_type_name: Red Hat Ansible Automation Platform
    inputs:
      oauth_token: "{{ controller_token.token }}"
      host: "https://{{ _automation_controller_hostname }}/api/controller/"

- name: Add project in EDA
  ansible.eda.project:
    controller_username: "{{ _automation_controller_username }}"
    controller_password: "{{ _automation_controller_password }}"
    controller_host: "https://{{ _automation_controller_hostname }}"
    validate_certs: false
    name: Cisco Telemetry
    organization: Default
    url: https://github.com/zjpeterson/ansible-cisco-telemetry.git

- name: Add upstream DE
  ansible.eda.decision_environment:
    controller_username: "{{ _automation_controller_username }}"
    controller_password: "{{ _automation_controller_password }}"
    controller_host: "https://{{ _automation_controller_hostname }}"
    validate_certs: false
    name: Quay DE
    organization: Default
    image_url: quay.io/ansible/ansible-rulebook:v1.1.3
