---
- name: Tasks as root
  become: true
  become_user: root
  block:
    - name: Install packages
      ansible.builtin.dnf:
        name:
          - java-17-openjdk
          - python3-pip
        state: present

    - name: Don't use a stdout callback
      ansible.builtin.lineinfile:
        path: /etc/ansible/ansible.cfg
        regexp: '^stdout_callback'
        state: absent

    - name: Pull YANG Suite image
      containers.podman.podman_image:
        name: quay.io/zachp/yangsuite

- name: Tasks as student
  become: true
  become_user: student
  block:
    - name: Install python dependencies
      ansible.builtin.pip:
        executable: pip3
        state: present
        name:
          - ansible-rulebook
          - ansible-pylibssh
          - psycopg[binary]
          - aiokafka
          - paramiko

    - name: Install collections
      ansible.builtin.command:
        cmd: ansible-galaxy collection install ansible.eda cisco.ios git+https://github.com/zjpeterson/network.telemetry.git
        creates: /home/student/.ansible/collections/ansible_collections/network/telemetry

    - name: Pull down git repo
      ansible.builtin.git:
        repo: https://github.com/zjpeterson/ansible-cisco-telemetry.git
        dest: /home/student/telemetry

    - name: Remove repo files not needed
      ansible.builtin.file:
        path: /home/student/telemetry/{{ item }}
        state: absent
      loop:
        - .git
        - workshop
        - README.md

    - name: Copy inventory
      ansible.builtin.copy:
        src: /home/student/lab_inventory/hosts
        dest: /home/student/telemetry/inventory
        remote_src: true

    - name: Pull lab EE
      containers.podman.podman_image:
        name: quay.io/zachp/lab-ee:latest

    - name: Change default EE
      ansible.builtin.replace:
        path: /home/student/.ansible-navigator.yml
        regexp: '(^\s*image:\s*)quay\.io/acme_corp/network-ee:latest'
        replace: '\1quay.io/zachp/lab-ee:latest'
  
    - name: Apply ansible-navigator defaults
      ansible.builtin.blockinfile:
        dest: /home/student/.ansible-navigator.yml
        block: |
          {% filter indent(width=2, first=true) %}
          mode: stdout
          playbook-artifact:
            enable: false
          {% endfilter %}
